# fly.toml app configuration file for OBB Zeitgeist
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'obb-zeitgeist'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '30s'

[experimental]
  auto_rollback = true

[build]

[env]
  PORT = '6020'

[[mounts]]
  source = 'obb_zeitgeist_data'
  destination = '/app/data'

[http_service]
  internal_port = 6020
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '30s'
    timeout = '30s'
    grace_period = '60s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1